main/pr
tricoderu/12dockerfile pull request #1
Opened 2024-09-28 15:00 UTC by tricoderu

2024-09-28 15:09 UTC, tricoderu commented
то, что одни и те же файлы будут скопированы дважды неэффективно, но не критично, мне кажется.  Да, go.mod и go.sum будут кешироваться Docker'ом, но время сборки не увеличится благодаря кэшированию. EXPOSE пусть будет, это же принципиально ни на что не повлияет. Могу убрать

2024-09-28 18:37 UTC, dirtymew commented
> то, что одни и те же файлы будут скопированы дважды неэффективно, но не критично, мне кажется. Да, go.mod и go.sum будут кешироваться Docker'ом, но время сборки не увеличится благодаря кэшированию. EXPOSE пусть будет, это же принципиально ни на что не повлияет. Могу убрать

- не понял про файлы? 
- если приложение не сетевое зачем открывать порт?

2024-09-28 18:50 UTC, dirtymew requested changes
Привет 

Спасибо что оформил PR но в нем нет главного -  Dockerfile-а

все эти файлы можно влить в main а в ветке PR должны быть изменения в Dockerfile

2024-09-28 18:50 UTC, dirtymew commented on main.go
> +// main.go
дам комментарии так 

```
# Используем официальный образ Go как базовый образ
FROM golang:1.22.4 AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum в контейнер
COPY go.mod go.sum ./ # тут COPY . . 

# Загружаем зависимости
RUN go mod download

# Копируем весь код приложения
COPY . .   # это убрать

# Собираем приложение
RUN go build -o myapp .

# Используем небольшой образ для запуска приложения
FROM alpine:latest

# Переносим собранное приложение в новый образ
WORKDIR /root/ - # почему в  /root, а не /srv или /bin 
COPY --from=builder /app/myapp .

# Открываем порт
EXPOSE 8080 # убрать - зачем порт открывать в контейнере? 

# Указываем, какую команду выполнять в контейнере
CMD ["./myapp"]
```

2024-09-29 10:18 UTC, tricoderu commented on main.go
> +// main.go
Я изначально исходил из логики, что на этапе разработки использование root директории для работы может быть проще... и потом, насколько я понял, если мы запускаем контейнер с правами пользователя root (по умолчанию), то директория /root будет доступна, и объекты, созданные в ней, будут принадлежать только мне, разработчику (ну, типа это дев, а не продакшн). Согласен, это не совсем верная логика, перемудрил, какой тут уже дев. С другой стороны, если я правильно понял, то bin предназначена для хранения исполняемых системных (!) файлов (все же файловая система как бы, лучше не смешивать...).  Да, можно было бы использовать srv, ведь у нас тут вроде бы всего один сервис. Но сейчас мне кажется, что можно использовать /app (у нас тут один простой сервис). Я заменю вверху на dev, внизу на app.

Что касается "COPY go.mod go.sum", то я прочитал в теории про кеширование и исходил из логики, что стоит минимизировать количество повторных загрузок при изменении кода. Ну, то есть это поможет избежать повторного скачивания зависимостей при каждом обновлении кода. Может, все же лучше оставить это для оптимизации слоя кеша? Пока убрал...

2024-09-29 10:25 UTC, tricoderu commented on main.go
> +// main.go
"в нем нет главного - Dockerfile-а"
Похоже, что в прошлый раз Dockerfile не попал в PR потому что не сделал ни одного минимального изменения. Сейчас все ок.

2024-09-29 11:31 UTC, dirtymew commented on main.go
> +// main.go
"COPY go.mod go.sum" - все верно понял, мой комментарий был про другое

"COPY . . " скопирует все сразу в том числе и файлы go.mod go.sum -  те получится что мы копируем их 2 раза - они маленькие и в целом это никак на времени сборки не отразиться - просто в докерфайле будет меньше команд.

2024-09-29 11:32 UTC, dirtymew approved these changes
Привет 

все отлично - зачет

2024-09-29 11:32 UTC, dirtymew commented on Dockerfile
> +WORKDIR /dev
тут можно было и app оставить тоже)

2024-10-09 05:35 UTC, merged